### ISSUE TITLE
Move the map?

### ISSUE THREAD

**Issue by Desdemonique** [Nevcairiel/Mapster#12]
Unable to move Mapster, but I'm certain that previous versions allowed you to relocate where on your screen you wanted the map to sit.

**Comment by Nevcairiel** [comment]
You can move the map by grabbing it by any of its "frame" (click and hold, drag around), basically anywhere there is no actual map or any other button.

**Comment by yujingz** [comment]
@Desdemonique  had the same issue, mine is because ELVUI did some cosmetic thing on top of the map frame. Disable the zoom options in elvui fixed it
