### ISSUE TITLE
Half map only

### ISSUE THREAD

**Issue by Wandat** [Nevcairiel/Mapster#17]
Hi,

I install mapster classic and then I see that (click on Thumbnail for full screen picture):

<a href="https://www.directupload.net/file/d/5580/57rd8js2_jpg.htm" target="_blank"><img src="https://s17.directupload.net/images/190919/temp/57rd8js2.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

No other Adds are installed. What can I do for see the whole map?

Thank you für help

LG

**Comment by Wandat** [comment]
Stille have the problem after install 1.8.5-classic

**Comment by usagicore** [comment]
I had same issue; Try scale UI all the way down and try again

**Comment by Wandat** [comment]
You mean the graphic interface? This do not help :(
