### ISSUE TITLE
Suggestion: Map zoom

### ISSUE THREAD

**Issue by Ghamarro** [Nevcairiel/Mapster#19]
Hi,
Would it be possible to have a zoom in and out feature for Mapster, kinda like Leatrix Maps has, where you can zoom in or out within a zone's map with mouse wheel scrolling? 

Just to clarify; when I say zoom out, I don't mean the default map UI zoom out feature where you can leave a zone view by pressing mouse 2 and watch the whole continent instead. 

The reason I'm suggesting this feature is because when using addons that show nodes on map for quest givers, it gets really crowded on really small and tight hubs and thus to distinguish one quest giver from another.

**Comment by Havenloft** [comment]
This is the only feature that has kept me using Leatrix over this addon. For the same reasons. Classic Codex has nodes on the map and I often have to zoom to see more clearly.

Think of it as the exact same functionality as zooming in and out on your Minimap display; but on your world map instead.

Glad to see this was already a suggestion here.

**Comment by Nevcairiel** [comment]
Map Zoom is typically provided by the Blizzard map, at least on  Retail. For some reason they decided to not offer it on Classic, and I do not plan to re-implement it only for classic.
