### ISSUE TITLE
Map does not stay in position after closing

### ISSUE THREAD

**Issue by vinajuliette** [Nevcairiel/Mapster#2]
Opening the map defaults it to the center of the screen. If you move the map, close it, then re-open it, it will move back to it's default position.
Opening the map as the quest log does not have this same problem. That is, I can open the quest log, move it around, close it, and it is in the position I left it when I closed it.

I'm unsure what the issue would be but the two windows are virtually identical except the quest log window opens the map with the log visible.

Note: This is NOT a problem with the same version on the WoW Classic 1.13.2 (stress test) for Mac using this addon.

The error is only on the 8.2 live retail for Mac client.

**Comment by Nevcairiel** [comment]
This works just fine for me. The usual cause for this issue is other addons interfering with the map.

**Comment by vinajuliette** [comment]
Ok I think I have that installed too. I'll disable it and give it a try and report back

**Comment by Nevcairiel** [comment]
I believe WQT might even have a setting somewhere that says something like "move map to center" or something like that.

**Comment by vinajuliette** [comment]
Ok yes, under the status bar > Map Window Centralized. I unchecked that, it reloaded the UI and now the window stays where I moved it. Thanks!
