### ISSUE TITLE
Addition: Anchoring the map 

### ISSUE THREAD

**Issue by Riverstar907** [Nevcairiel/Mapster#27]
I'm sorry if this isn't formatted correctly etc, I'm still trying to figure out Github.

If possible, I would like to see a feature that allows the map to stay in the place I dragged it so after I close the map and open it again, it's where I left it and not centered/blocking my view while traveling. Thank you for an awesome addon!

**Comment by Nevcairiel** [comment]
Mapster already does this, but there are a bunch of addons that you wouldn't suspect that actually reset the map position for unknown reasons.
