### ISSUE TITLE
Taint error

### ISSUE THREAD

**Issue by reaper666735** [Nevcairiel/Mapster#31]
Hello, 

recently been getting this is my taint log,

7/3 12:03:18.774  Interface\AddOns\Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua:48 ShouldShowUnit()
7/3 12:03:18.774  An action was blocked in combat because of taint from Ace3 - <unnamed>:SetHorizontalScroll()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:700 <unnamed>:SetNormalizedHorizontalScroll()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:631 <unnamed>:InstantPanAndZoom()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:614 <unnamed>:ResetZoom()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:423 <unnamed>:OnCanvasSizeChanged()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:42 WorldMapFrame:OnFrameSizeChanged()
7/3 12:03:18.774      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:342 WorldMapFrame:UpdateSpacerFrameAnchoring()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:138 WorldMapFrame:SetDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:41 WorldMapFrame:HandleUserActionToggleSelf()
7/3 12:03:18.774      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:432 ToggleWorldMap()
7/3 12:03:18.774      TOGGLEWORLDMAP:1
7/3 12:03:18.774  Interface\AddOns\Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua:48 ShouldShowUnit()
7/3 12:03:18.774  An action was blocked in combat because of taint from Ace3 - <unnamed>:SetVerticalScroll()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:709 <unnamed>:SetNormalizedVerticalScroll()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:632 <unnamed>:InstantPanAndZoom()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:614 <unnamed>:ResetZoom()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:423 <unnamed>:OnCanvasSizeChanged()
7/3 12:03:18.774      Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:42 WorldMapFrame:OnFrameSizeChanged()
7/3 12:03:18.774      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:342 WorldMapFrame:UpdateSpacerFrameAnchoring()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:138 WorldMapFrame:SetDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:41 WorldMapFrame:HandleUserActionToggleSelf()
7/3 12:03:18.774      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:432 ToggleWorldMap()
7/3 12:03:18.774      TOGGLEWORLDMAP:1
7/3 12:03:18.774  Interface\AddOns\Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua:48 ShouldShowUnit()
7/3 12:03:18.774  An action was blocked in combat because of taint from Mapster - WorldMapFrame:SetScale()
7/3 12:03:18.774      Interface\AddOns\Mapster\Mapster.lua:199 SetScale()
7/3 12:03:18.774      Interface\AddOns\Mapster\Mapster.lua:213
7/3 12:03:18.774      SynchronizeDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:141 WorldMapFrame:SetDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:41 WorldMapFrame:HandleUserActionToggleSelf()
7/3 12:03:18.774      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:432 ToggleWorldMap()
7/3 12:03:18.774      TOGGLEWORLDMAP:1
7/3 12:03:18.774  Interface\AddOns\Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua:48 ShouldShowUnit()
7/3 12:03:18.774  An action was blocked in combat because of taint from Mapster - 
7/3 12:03:18.774      Interface\AddOns\Mapster\Libs\LibWindow-1.1\LibWindow-1.1.lua:178 RestorePosition()
7/3 12:03:18.774      Interface\AddOns\Mapster\Mapster.lua:183 SetPosition()
7/3 12:03:18.774      Interface\AddOns\Mapster\Mapster.lua:215
7/3 12:03:18.774      SynchronizeDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:141 WorldMapFrame:SetDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:41 WorldMapFrame:HandleUserActionToggleSelf()
7/3 12:03:18.774      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:432 ToggleWorldMap()
7/3 12:03:18.774      TOGGLEWORLDMAP:1
7/3 12:03:18.774  Interface\AddOns\Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua:48 ShouldShowUnit()
7/3 12:03:18.774  An action was blocked in combat because of taint from Mapster - WorldMapFrame:ClearAllPoints()
7/3 12:03:18.774      Interface\AddOns\Mapster\Libs\LibWindow-1.1\LibWindow-1.1.lua:190 RestorePosition()
7/3 12:03:18.774      Interface\AddOns\Mapster\Mapster.lua:183 SetPosition()
7/3 12:03:18.774      Interface\AddOns\Mapster\Mapster.lua:215
7/3 12:03:18.774      SynchronizeDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:141 WorldMapFrame:SetDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:41 WorldMapFrame:HandleUserActionToggleSelf()
7/3 12:03:18.774      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:432 ToggleWorldMap()
7/3 12:03:18.774      TOGGLEWORLDMAP:1
7/3 12:03:18.774  Interface\AddOns\Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua:48 ShouldShowUnit()
7/3 12:03:18.774  An action was blocked in combat because of taint from Mapster - WorldMapFrame:SetPoint()
7/3 12:03:18.774      Interface\AddOns\Mapster\Libs\LibWindow-1.1\LibWindow-1.1.lua:202 RestorePosition()
7/3 12:03:18.774      Interface\AddOns\Mapster\Mapster.lua:183 SetPosition()
7/3 12:03:18.774      Interface\AddOns\Mapster\Mapster.lua:215
7/3 12:03:18.774      SynchronizeDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:141 WorldMapFrame:SetDisplayState()
7/3 12:03:18.774      Interface\FrameXML\QuestLogOwnerMixin.lua:41 WorldMapFrame:HandleUserActionToggleSelf()
7/3 12:03:18.774      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:432 ToggleWorldMap()
7/3 12:03:18.774      TOGGLEWORLDMAP:1

**Comment by Nevcairiel** [comment]
The map is not protected by default. It is likely that you have an addon that attaches something to the map which makes it protected. If it started lately, what did you install?

**Comment by reaper666735** [comment]
i believe it could be Zone Info 2 then ( https://www.curseforge.com/wow/addons/zoneinfo-2 ), i already posted the same log on there as well, i also came to the conclusion that it could be a "mixing" issue since it does add an info frame to the world map, and Mapster being used in conjunction ..... well we get this result :p

**Comment by Nevcairiel** [comment]
I can confirm that ZoneInfo2 has indeed a secure button on its panel - even though it really doesn't need it. Secure Buttons are only useful if you want to cast spells or whatnot - it uses it to lock its panel in place. That causes the entire map to become protected due to the secure button, and all the taint errors show up.

**Comment by reaper666735** [comment]
ty for your help, i have already seen you posted on my ticket for ZI 2 regarding this issue :)
