### ISSUE TITLE
NPC's not showing on map on 1 of my 2 accounts - Classic WoW

### ISSUE THREAD

**Issue by Myskully14** [Nevcairiel/Mapster#35]
Hey. I have two accounts attached to one battle.net account. When I download an addon via Twitch (Used to be Curse Client) I only download it once and it activates on both WoW accounts. Mapster works on both accounts except for one thing... the NPC functionality does not work on one of the two accounts... across all characters. The NPC functionality works on all characters on the other account. This includes all NPC options... such as Mailbox, Repairs, Class Trainers, ETC. It's as if the first "Show" option in the NPC dropdown menu is turned off. I have attempted to turn that option off and back on... disabled and re-enabled the addon... and reloaded many times as this problem has existed for a long time. All addons I use are shared across both accounts. As in... I don't have any addons enabled on account 1 that I do not have enabled on account 2. I only have one other map modifying addon... Questie... and it works fine on both accounts. By the way... the NPC markers do not appear on the main map or mini map and I have checked to make sure the Interface options are identical between both accounts.

Is there anything that might fix this issue?

**Comment by Myskully14** [comment]
This was not completed. No answer was ever given.

**Comment by Nevcairiel** [comment]
WoW Classic is no longer supported by Mapster, there is no answer to give.
