### ISSUE TITLE
Only BfA map is showing

### ISSUE THREAD

**Issue by Grizzabelle** [Nevcairiel/Mapster#37]
i'm leveling via Chromie time.  I've just hit 46.  when opening map i only see BfA map.  I have to click to zoom out then pick the legion area and then click to zoom in for where I am.  

my map also no longer shows my class hall when i'm there

this just started happening.  

logging out and then back in did not fix.

I don't know if this is a WoW issue or a Mapster issue.

**Comment by Grizzabelle** [comment]
something with the addon World Quest Tracker is messing with Mapster.  i have narrowed it down to that.

**Comment by Nevcairiel** [comment]
World Quest Tracker is known for notorious map mishandling. Mapster itself does not actually influence the map selection on the map, it just makes the frame movable, resizeable, adds coordinates, etc.

**Comment by Grizzabelle** [comment]
Once I killed WQT, I realized what was going on.  Sadly I had already been here and commented.   I did comment over there, under some other post, asking a question.  but never heard anything.  I do see today there's an update.  

I do wanna say thanks for the quick reply, I love this addon, probably one I couldn't play without.  keep up the great work!
