### ISSUE TITLE
FogClear not working in latest version

### ISSUE THREAD

**Issue by Spotnick2** [Nevcairiel/Mapster#38]
This is in WOW Classic, rollbacking to previous version works.

Message: Interface\AddOns\Mapster\FogClear.lua:103: attempt to index upvalue 'FogData' (a nil value)
Time: Fri Oct 30 02:18:21 2020
Count: 1
Stack: Interface\AddOns\Mapster\FogClear.lua:103: attempt to index upvalue 'FogData' (a nil value)
...haredMapDataProviders\MapExplorationDataProvider.lua:163: in function `?'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:510: in function `CallMethodOnPinsAndDataProviders'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:542: in function `OnCanvasScaleChanged'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:634: in function `InstantPanAndZoom'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:614: in function `ResetZoom'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:423: in function `OnCanvasSizeChanged'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:407: in function `SetMapID'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:33: in function `SetMapID'
...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:138: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:136>
[C]: ?
[C]: ?
[C]: ?
...e\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:95: in function <...e\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:87>
[C]: in function `Show'
Interface\AddOns\Mapster\Mapster.lua:111: in function <Interface\AddOns\Mapster\Mapster.lua:111>
(tail call): ?
...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:174: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals: self = <unnamed> {
 SetNudgeSourceMagnitude = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:166
 GetGlobalPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:253
 PanTo = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:260
 owningMap = WorldMapFrame {
 }
 OnCanvasScaleChanged = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\MapExplorationDataProvider.lua:161
 GetNudgeSourceZoomedInMagnitude = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:175
 SetScaleStyle = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:301
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:211
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:199
 ApplyFrameLevel = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:374
 ApplyCurrentPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:336
 IsIgnoringGlobalPinScale = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:287
 textureLoadGroup = <table> {
 }
 overlayTexturePool = <table> {
 }
 RefreshMouseOverOverlays = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\MapExplorationDataProvider.lua:167
 OnMouseEnter = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:122
 pinTemplate = "MapExplorationPinTemplate"
 OnMouseUp = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:134
 OnAcquired = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:110
 PanAndZoomTo = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:265
 ApplyCurrentScale = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:340
 OnLoad = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\MapExplorationDataProvider.lua:52
 OnReleased = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:114
 RemoveAllData = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\MapExplorationDataProvider.lua:60
 RefreshA

------------

Message: Interface\AddOns\Mapster\FogClear.lua:103: attempt to index upvalue 'FogData' (a nil value)
Time: Fri Oct 30 02:18:21 2020
Count: 1
Stack: Interface\AddOns\Mapster\FogClear.lua:103: attempt to index upvalue 'FogData' (a nil value)
[C]: in function `Show'
Interface\AddOns\Mapster\Mapster.lua:111: in function <Interface\AddOns\Mapster\Mapster.lua:111>
(tail call): ?
...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:174: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals: (*temporary) = WorldMapFrame {
 0 = <userdata>
 ShouldPanOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:622
 GetGlobalPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:489
 PanTo = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:589
 AreDetailLayersLoaded = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:403
 RemovePin = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:182
 OnCanvasScaleChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:533
 CalculatePinNudging = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:301
 OnCanvasSizeChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:549
 HandleUserActionToggleSelf = <function> defined @Interface\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:100
 SetAreaTriggerIntersectsCallback = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:247
 ShouldZoomInstantly = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:630
 expandedMapInsetsByMapID = <table> {
 }
 pinNudgingDirty = true
 SetGlobalPinScale = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:771
 RefreshDebugAreaTriggers = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:356
 SetShouldNavigateOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:610
 NavigateToParentMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:720
 SetDebugAreaTriggersEnabled = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:380
 mapArtID = 1267
 EvaluateLockReasons = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:692
 GetGlobalPinScale = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:767
 OnLoad = <function> defined @Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:13
 RemoveDataProviderEvent = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:95
 GetNumActivePinsByTemplate = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:198
 SetPinTemplateType = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:171
 SetAreaTriggerEnclosedCallback = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:242
 IsCanvasMouseFocus = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:678
 GetCanvasScale = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:553
 SetGlobalAlpha = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:784
 RemoveDataProvider = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:84
 lockReasons = <table> {
 }
 GetScaleForMinZoom = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:650
 NavigateToCursor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:727
 AdjustDetailLayerAlpha = <function> defined @Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:412
 RegisterCallback = <function> defined @Interface\SharedXML\Util.lua:993
 UnregisterCallback = <function> defined @In

----------

Message: Interface\AddOns\Mapster\FogClear.lua:103: attempt to index upvalue 'FogData' (a nil value)
Time: Fri Oct 30 02:18:21 2020
Count: 3
Stack: Interface\AddOns\Mapster\FogClear.lua:103: attempt to index upvalue 'FogData' (a nil value)

Locals:

**Comment by Nevcairiel** [comment]
Make sure you installed the Classic version of the addon, and not the Retail version. That would explain it not finding any data.

**Comment by Spotnick2** [comment]
> Make sure you installed the Classic version of the addon, and not the Retail version. That would explain it not finding any data.

I will check that, if that's the problem it's once again curse mixing up addons
