### ISSUE TITLE
World map position issue

### ISSUE THREAD

**Issue by Revnn** [Nevcairiel/Mapster#42]
When i open my world map and i try to select a zone, the zone selected is not the one im placing my cursor on.
See this SS, its selecting orobos, but my cursor is no where near orobos, its all shifted, i cant select bastion at all for exemple, I marked where my cursor is ingame since the SS doesnt capture the cursor.
`https://imgur.com/eWkxLQl`

**Comment by UltraVolta425** [comment]
I would like to confirm this, very annoying bug.

https://imgur.com/a/z3Khoch
In the screenshot, I have to aim at Terrokar Forest to get Mapster to think that I'm pointing at Netherstorm.
Other zones are completely untargetable, basically everything on the bottom half of whatever map I currently have open.

**Comment by Nevcairiel** [comment]
This is being caused by other addons messing with the map. You seem to be using the same UI with the yellow coordinate display, which is a likely culprit.

**Comment by UltraVolta425** [comment]
Of course, I should have realized!
Because I'm using the Mapster addon, I should of course disable ElvUI's map module entirely. Works flawlessly now, thank you for pointing that out. :)
