### ISSUE TITLE
Fog Clear on ClassicTBC Prepatch.

### ISSUE THREAD

**Issue by Nerillida** [Nevcairiel/Mapster#48]
Not working
Redownloaded
Saved variables cleared

Thanks,

**Comment by junchao-1837136** [comment]
I have the same issue.

**Comment by Nerillida** [comment]
Leatrix works for now.

**Comment by Ergates82** [comment]
Same problem here. Fog of war remains no matter what I do.  The other poster appears to have found a solution, could it please be shared?

**Comment by Nerillida** [comment]
Leatrix on curse forge has Fog clear.

**Comment by Ergates82** [comment]
Thanks, I'll check it out. I saw your other post, but didn't know what Leatrix was, thought it was the name of one of the mod authors or something.

**Comment by Nerillida** [comment]
:)
