### ISSUE TITLE
Top of map is off screen

### ISSUE THREAD

**Issue by derrickb** [Nevcairiel/Mapster#55]
Just installed Mapster 1.9.5-bcc for the first time. Opened the map and the top of it extends above the game window, both fullscreen and windowed. Buttons for other addons (Questie, Atlas) are only just barely visible.

Is there a way to reset the map size and location?

![image](https://user-images.githubusercontent.com/1793769/137762508-4774470b-0c04-4855-9491-07a0f802d9c9.png)

**Comment by Wandat** [comment]
For a long time I had this problem too, no one helped me.

By chance I found the solution: with the corner at the bottom right you can drag the card down. You really have to use the outermost corner, try several times.

**Comment by Nevcairiel** [comment]
As said above, just drag it back or resize it as needed

**Comment by lucaswj** [comment]
still a problem in July 2024
