### ISSUE TITLE
Broken with Wrath

### ISSUE THREAD

**Issue by phaiz** [Nevcairiel/Mapster#58]
Seems that this is broken with Wrath pre-patch, but in addition to it not removing the fog of war you are unable to navigate the world map - you can right click to zoom out but you can not click any continent or zones.

**Comment by phaiz** [comment]
Renaming the toc does remove the fog and the map seems to work correctly when at zone level, but zooming out to region and world levels breaks it.  My cursor has to be at the bottom of the map to select zones in the middle, and I am unable to highlight or click zones at the bottom of the map.

**Comment by kazso** [comment]
I don't have this problem. Zooming in and out, highlighting and clicking on zones works fine for me. Either another addon, or some Mapster setting might cause this issue for you.
Try to disable every addon except Mapster and/or delete your Mapster settings (Mapster.lua and Mapster.lua.bak files in WTF folder, make a backup before deleting).
