### ISSUE TITLE
Map out of alignment

### ISSUE THREAD

**Issue by Destruo** [Nevcairiel/Mapster#59]
This is in Wrath Pre-Patch

Certain areas of the world map on continents are off point

For example for me to click on Eastern Kingdoms I need to click at least 2cm to the right of EK in order for me to view the continent.

**Comment by Nevcairiel** [comment]
As far as I can tell, this is caused by other mods messing with the map. One I was told about is Tomcat Tours, or whatever its called. If you are running that, try getting rid of it.

**Comment by Destruo** [comment]
Hi thanks for the quick reply. I don't use Tomcat Tours but have done some checking and after disabling addons it appears that ElvUI is causing the issue itself.

**Comment by Destruo** [comment]
After further investigation it actually appear to only happen when you scale the map bigger or smaller. I reset my profile on the map and is fine.

**Comment by Nevcairiel** [comment]
That seems likely. Mapster tries to fix the mouse interaction when you scale (because its required to do that), if that fixing gets somehow broken by another mod, it would be off.

**Comment by Nevcairiel** [comment]
As was stated above, this works fine if Mapster is the only map addon loaded. There is nothing I can do if other addons interfer with the process. Mapsters ability to rescale the map requires it to try to fix the click positions, and this works if Mapster is alone. If other mods break that, there is little I can do.

I have confirmed just now that with Mapster loaded alone, it works fine. It also continues to work fine with my other addons loaded. Whatever other addons you have however, might mess with it. I've heard that ElvUI can do it. And also as mentioned above Tomcat Tours.
