### ISSUE TITLE
Map interaction offset

### ISSUE THREAD

**Issue by ExiledDitto** [Nevcairiel/Mapster#6]
In Classic WoW when hovering over any part of the map, to change zones or to hover a poi, the place being targeted is actually a few inches up and to the right. This only affects the map itself. Any other addon that adds waypoints and markers will function properly.

https://puu.sh/Eb8e3/e7663d71a3.jpg

https://puu.sh/Eb8fz/af1fdd931d.jpg

**Comment by Nevcairiel** [comment]
This works just fine for me. You are on 1.8.4 right? There was a scaling bug I fixed in that version that would cause that. Otherwise I can only assume another addon might be interfering.

**Comment by ExiledDitto** [comment]
Ah, you are correct, it was TomCat Tours. I didn't realize that addon was changing the entire map frame, so I didn't even think of checking it. Sorry for wasting your time.
