### ISSUE TITLE
Quest Tabs are behind map instead of on the side

### ISSUE THREAD

**Issue by BurnyTrash** [Nevcairiel/Mapster#60]
I noticed when I started to walk with the map open and it became transparent that the quest side tabs were behind the map instead of on the side and bottom. I checked all of my addons by turning them all off to see if any affected it and none of them did.
![wow map solid](https://user-images.githubusercontent.com/114691359/193107816-388a6b31-7b94-4402-bf94-4513213b96a6.png)
![wow map transparent](https://user-images.githubusercontent.com/114691359/193107821-09a693b7-2ab0-4cc7-a7c3-1f42ae32f5c4.png)

**Comment by Nevcairiel** [comment]
Transparency can show whats hidden behind the map. Can't really change that.
