### ISSUE TITLE
enhancement: hide artwork

### ISSUE THREAD

**Issue by Daeveren** [Nevcairiel/Mapster#66]
Suggestion: add an option to hide the entire top part of the map, for a minimalistic "map-only" option. The titlebar and the zone location browser (World > The Shadowlands > Ardneweald > Heart of the Forest) are so rarely used that they tend to just take screen real estate for nothing.
This could potentially be achieved with either a toggle in the addon settings, either via a new 'up/down arrow' button above the map, which would expand/collapse the entire top part of the map window.

![image](https://user-images.githubusercontent.com/6321337/199925728-31c8eb66-e185-40c3-a44f-2bd44a5f5506.png)

**Comment by Nevcairiel** [comment]
Mapster used to have this feature, but it was extremely maintenance intensive and caused issues with other mods and the default UI alike. So not likely to bring it back, sorry.
