### ISSUE TITLE
Fade settings not working

### ISSUE THREAD

**Issue by JakobDylanC** [Nevcairiel/Mapster#7]
Map isn't turning transparent when setting is turned on

**Comment by quadrotony** [comment]
same here

**Comment by EnragedN3wb** [comment]
My map turns transparent, but that may be due to the Cvar setting in AdvancedInterfaceOptions. 

The Faded Alpha setting does not work though. =\

**Comment by EnragedN3wb** [comment]
Update on this...

The faded alpha setting will work until the map is closed & reopened. Then it goes back to default fade amount even though the setting still says what you set it to.
