### ISSUE TITLE
Mouse Cursor seems off

### ISSUE THREAD

**Issue by zaphon** [Nevcairiel/Mapster#70]
If you open Mapster (I have the window resized) and you right click on the map to show the rest of the continent, if you try and mouse over another zone it doesn't highlight the zone you're over. I've tried resizing the map, etc. and I can't find a way to get the coordinates to match up.

**Comment by Nevcairiel** [comment]
Mapster by itself will try to compensate for size changes. Other addons have a history of breaking this. Unfortunately there is nothing I can do to prevent other addons from interfering.

**Comment by Dhisanas** [comment]
1.10.1 doesn't seems to have that problem tho, just had to revert after the latest to 1.10.2 update.
