### ISSUE TITLE
You forgot to reset map scaling

### ISSUE THREAD

**Issue by TinyTrbl** [Nevcairiel/Mapster#71]
You forgot to fully disable map scaling OR just reset ["scale"] back to 1 in Mapster.lua 

`["scale"] = 1.0,` or something like this

And as a follow-up Mapster went into broken state with broken cursor interactions for users who had custom scale enabled.
Just like here https://github.com/Nevcairiel/Mapster/issues/70

On a side note i never got any these reported LUA errors with 10.0 Mapster with _updated_ addons and i have a lot of enabled addons trust me hehe. So thanks to those "false" reports now we have disabled scaling i.e. one useful future is gone. :(

**Comment by Nevcairiel** [comment]
I do not make any changes based on reports I cannot reproduce.

**Comment by artazika** [comment]
same here, none errors from mapster
I rolled back to the previous version with a working scale

**Comment by Nevcairiel** [comment]
If you want to see the start of a failure, just open the map, change zone by right clicking on the map or something like that, then press escape and open edit mode, and close it again. You'll instantly get a blocked action error, every single time.

While you may say Edit Mode being broken is not important to me, this sort of issue can spread to a lot of different places in the UI, and result in actual issues in combat.

**Comment by artazika** [comment]
yes, I returned the scale of the map to 100% on the old version, then I updated it and the bug with incorrect display of the cursor disappeared

but that's just disabling half of the benefits of the mapster. I'm probably stuck with the old version sadly

**Comment by Nevcairiel** [comment]
The scale was reset in 1.10.3

Note that I'm not happy about removing the scale feature, and hopefully its not permanent, but having the addon break the UI is not acceptable in any way or form.

**Comment by artazika** [comment]
after several tests I also got same bug when I moved map window
