### ISSUE TITLE
map scale removed

### ISSUE THREAD

**Issue by Daeveren** [Nevcairiel/Mapster#72]
Is there hope to bring back map scaling before Dragonflight? Is an alternative scaling method being worked on?
Thanks for your addon!

**Comment by Gaviin1242** [comment]
Yeah I'm reverting to an older version that still has the scaling.  I haven't had any errors or issues, and scaling is too essential to live without.  :)

**Comment by chrislima** [comment]
why did they remove this?

**Comment by jlschuncke** [comment]
I could live with not being able to rescale the map if I could just once resize my map to something I could read.

I shrunk it to fit off in the side temporarily and now it's stuck unusably small. Either I squint or I full-screen the map, neither of which is a good look.

**Comment by Daeveren** [comment]
> I could live with not being able to rescale the map if I could just once resize my map to something I could read.
> 
> I shrunk it to fit off in the side temporarily before 10.0 dropped and now it's stuck unusably small. Either I squint or I full-screen the map, neither of which is a good look.

I'm in the same boat. It's unusably small and the elements on map also hard to read or observe. Fullscreen map has the same issues. I'm playing at 1440p.

**Comment by Nevcairiel** [comment]
The size was reset to 100% for everyone, your previous size setting does not matter.

I may add a checkbox to enable scaling for those that are happy to deal with some UI breakage once in a while, but having that breakage for everyone even if they don't use scaling is not good.

**Comment by chrislima** [comment]
> The size was reset to 100% for everyone, your previous size setting does not matter.
> 
> I may add a checkbox to enable scaling for those that are happy to deal with some UI breakage once in a while, but having that breakage for everyone even if they don't use scaling is not good.

Please make the checkbox 👯

**Comment by Treacherouz** [comment]
I too rely heavily on the scale feature, and would love to see this checkbox implemented as to not be stuck on an old version! Thanks in advance!

**Comment by Nifelhein** [comment]
I would like to indicate my support on having a checkbox to enable scaling as well. With warnings and everything you may consider necessary.

**Comment by Nevcairiel** [comment]
The latest alpha version already implements the checkbox talked about here.

Note that the issues can be as bad as your action bars no longer working at all - that is, if you use the default UI action bars. Addons like Bartender4 are immune to that particular issue. So if you use default UI action bars, be warned.

**Comment by RandethCorinth** [comment]
Thanks for the warning. I've run into the issue you are talking about a lot. I even made a macro to Reload the UI, which tends to fix the issue until I zone or switch characters. 

I really hope there is a permanent fix to this eventually. Thanks for the hard work on this.

**Comment by Nevcairiel** [comment]
For those still here - 10.0.5 PTR today added a change that will allow to re-enable the scaling for everyone without any risk of breaking the map. Rejoice (once it goes live)!

**Comment by Gaviin1242** [comment]
Nice!  Looking forward to it.  :)

**Comment by Nevcairiel** [comment]
Scale is now available without an option again
