### ISSUE TITLE
[ADDON_ACTION_BLOCKED]

### ISSUE THREAD

**Issue by Edwin18** [Nevcairiel/Mapster#8]
1x [ADDON_ACTION_BLOCKED] Модификация 'Mapster' пыталась вызвать защищенную функцию 'CompactRaidFrame1:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearAllPoints'
FrameXML\FlowContainer.lua:157: in function `FlowContainer_DoLayout'
FrameXML\FlowContainer.lua:17: in function `FlowContainer_ResumeUpdates'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185: in function `CompactRaidFrameContainer_LayoutFrames'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string"*:OnEvent"]:1>

Locals:
InCombatSkipped

![image](https://user-images.githubusercontent.com/8036656/64063019-4070b680-cbf7-11e9-970b-5f190ea9db1d.png)

**Comment by Nevcairiel** [comment]
I know the error says Mapster, but the game likes to be wrong about that sort of thing. Raid Frames and the map are really not even related, so I doubt its actually at fault.
