### ISSUE TITLE
Mapster Wrath is broken

### ISSUE THREAD

**Issue by Velarax** [Nevcairiel/Mapster#84]
ICC patch broke it.  Can you fix it?  Map is not displaying properly, scaling properly, is not moveable and doesn't work.

**Comment by Kyung783** [comment]
+1

**Comment by Oldman68** [comment]
+1

**Comment by zkl94** [comment]
does anyone have alternatives for mapster before this is fixed?

**Comment by Oldman68** [comment]
"Enhanced World Map for WoW Classic"

**Comment by soest009** [comment]
+1

**Comment by ado21** [comment]
+1

**Comment by kazso** [comment]
> does anyone have alternatives for mapster before this is fixed?

Leatrix Maps

**Comment by ablib2** [comment]
> > does anyone have alternatives for mapster before this is fixed?
> 
> Leatrix Maps

Leatrix has been screwed up as well.  With every new Leatrix update I'm hoping for fixes, but it still hasn't improved much.  Weird zoom levels, missing map border, maps opening up huge and off my screen so I can't resize it, Map opening up by itself when I login.

The Wrath update in general seems to have really messed with maps.  Probably to add the new questing UI.

**Comment by soest009** [comment]
Is this addon considered dead now since no reaction from owners?

**Comment by Nevcairiel** [comment]
I have never played Classic, and when Blizzard figures re-evolving the UI is the best use of their time, its certainly not the best use of my time to try to fix it.

Mapster for Classic is basically discontinued now.
