### ISSUE TITLE
Map Sizing

### ISSUE THREAD

**Issue by ramirezjohn** [Nevcairiel/Mapster#9]
When trying to resize the map, the panel with get smaller or bigger, but the map itself will stay the same. Not sure if it was designed that way, but doesn't seem like it.

**Comment by Nevcairiel** [comment]
This works fine for me. Make sure you're not using another addon that might mess up the map. I've been told that for example Tomcat's Tours can cause such issues.

**Comment by ramirezjohn** [comment]
Ah. I am in fact using Tomcat's. I will go ahead and remove that. Thank you!
