### ISSUE TITLE
Isle of Dorn map broken after 11.0.7 patch

### ISSUE THREAD

**Issue by RShadowhand** [Nevcairiel/Mapster#98]
11.0.7 patch has introduced a new map piece to Isle of Dorn, you can see the result.

![image](https://github.com/user-attachments/assets/c6aa67c1-37cb-4c9c-9f1d-18a32e1d7e9b)

**Comment by Gnathach** [comment]
seeing the same thing.  On another toon it extended into the island.  Found it's an issue with the FogClear.  Turning it off makes it go away, but then of course alts have to deal with hidden map.
